### ISSUE TITLE
New opened tabs can be invisible without scrolling

### ISSUE THREAD

**Issue by Jiehong** [eoger/tabcenter-redux#135]
Hi,

Sometimes, if you have a long list of tabs, and open some new ones at the bottom of the list, they will be added to the list, but bellow your current tab, and they will be off screen.

This loses the visual indicator showing that the new tab has been correctly opened.

After a tab is created, would it be possible to have the sidebar automatically scroll down to show the newly opened tab?

**Comment by eoger** [comment]
It should do that already per https://github.com/eoger/tabcenter-redux/commit/93aefd2b0e0ef688404712fe8efef297a4aac8a4, can you maybe make a screencast?

**Comment by Jiehong** [comment]
Alright, I tried to screencast it:

![screencast](https://user-images.githubusercontent.com/1061229/29139507-836fad0c-7d47-11e7-9ed7-1097db37c874.gif)

In it, I open 2 tabs from the same link twice in a row (with right click to show it), and then show they are actually opened by scrolling.
Then, I open another tab again, with same result.

The screencast looks ugly, but I don't know why recording my screen shows many flashing images (of windows behind firefox.). Excuse-me for this.

If you need more information, here is the version of the extension used:
Tab Center Redux	0.4.1	true	{0ad88674-2b41-4cfb-99e3-e206c74a0076}

And some information about my system:
Firefox 55.0
Archlinux
Gnome 3.24.2

**Comment by eoger** [comment]
Okay I got it, this is because the new tab is not active: https://github.com/eoger/tabcenter-redux/blob/fba7cfcc409f686469d5c09f5317d46cf707683e/src/tablist.js#L440-L442

I would say this is intended behavior, but could be swayed if enough people complain about it.

**Comment by Jiehong** [comment]
Actually, the only issue here is that it is invisible, so no feedback that it was opened is given.
Not having a way to confirm that a new tab has been opened is the issue.

Scrolling down could be a way to give a feedback, but perhaps another kind of feedback would be possible?

The tab strip seems to have an animation each time a new tab is opened in background (the size of the tab length change slightly, indicating that another tab was added).

Perhaps scrolling down 1em, and back up 1em would indicate a new tab has been opened could work when the added tab is not visible?

**Comment by MrEricSir** [comment]
Just came across this on my own today. As a heavy user of Tab Center and other various side tab extensions over the years, I was surprised when I middle-clicked a link the new tab wasn't immediately noticeable.  Just like in the screencast from @Jiehong I found myself middle-clicking the link multiple times because I thought the new tab hadn't opened. 

I don't know enough about UI design to know _why_ I expect this particular behavior. That said, I have a hypothesis that it's somewhat unrelated to this extension. Vivaldi's side tabs behave exactly the same way, but the contrast on the scrollbar seems higher in Vivaldi than in Firefox. When a user-initiated change happens outside of the central focus of our vision, it needs to be visible enough that we can see something changing out of the corner of our eyes. The tab strip animation is a good example of this.
