### ISSUE TITLE
Why can't Tab Center continue to be used?

### ISSUE THREAD

**Issue by keehun** [eoger/tabcenter-redux#161]
Please forgive me posting here, as it probably isn't the best place, but I wanted to ask the community and have a discussion:

Why did Tab Center end at all? Was it a technical debt that Mozilla didn't want to continue supporting? Why can't an add-on be forked from Tab Center? Tab Center did exactly everything perfectly, and I am wondering why we're having the reinvent the technology.

Sorry if these questions have already been answered somewhere. I could not find the answers on my own through research.

Thank you,
Keehun

**Comment by yfdyh000** [comment]
Tab Center is not WebExtension.

**Comment by keehun** [comment]
So it was code built directly into the browser?

Then the next question is, why end it at all? Is it debt that Mozilla does not want to carry going forward without sufficient demand for it?

**Comment by yfdyh000** [comment]
https://github.com/bwinton/TabCenter, uses [Add-ons SDK](https://developer.mozilla.org/Add-ons/SDK) (jpm).

It is a Test pilot project, continue develops the project is odd that will not have a future, and conflicting to the goal of all WebExtensions. Anyone can continue to develops based on its source code, for Firefox 56 or earlier.

**Comment by csicky** [comment]
I understand that it was a test pilot project, still couldn't this extension be made to match the functionality exactly? I had an update to FF56 and now it's disabled. I tried this extension but it's not the same. Group Tabs extension is not respected. Button in window title bar to toggle horizontal/vertical is missing. After I switch this extension to dark theme it still has a big portion on top white. I closed it and there is no button to open it back. While it was open, the real tabs on top were still there.
All in all, this is much more beta version than the one it replaces.

**Comment by dos1** [comment]
@csicky Yes, this is a "much more beta version", as the extension needs to be completely rewritten using different technology than the old one to continue working with Firefox 57 and later.

It keeps getting better, but some of the tweaks can't be done automatically yet, as the new API lacks some of the required features. Fortunately, most of it can be reintroduced manually using userChrome.css file - see #103 and #118 for some references.

**Comment by dessant** [comment]
Mozilla has released some of their legacy extensions for Firefox 57+, see [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/), so they may have decided to deprecate Tab Center for a different reason than it not being a WebExtension. Hopefully they will share some details in the [report](https://testpilot.firefox.com/experiments/tab-center/) of the experiment.

Regardless of how polished Tab Center Redux is, currently it cannot compete with Tab Center because the required APIs are missing. One aspect which really gives it away is right-clicking on a tab shows a custom context menu, not the real one, so if a third-party extension places an item in the context menu of the tab, it will not be visible. The other one is the huge header at the top of the sidebar with the selector and close button.

**Comment by HaoZeke** [comment]
Why would they pull it from the AMO? o.O
I use cyberfox which is at v52.
But just to get this extension I had to compile it.

**Comment by eoger** [comment]
There's not much else to say here, closing.
