### ISSUE TITLE
Closing multiple tabs doesn't display close warning

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#93]
STR:
1. Make sure 'Warn you when closing multiple tabs' is enabled in Fx options
2. Open two or more tabs in the background
3. Right-click the current tab and select 'close tabs underneath'

ER:
Close confirmation popup should appear

AR:
No close confirmation

**Comment by eoger** [comment]
Web Extensions have no way of reading Firefox preferences.

**Comment by Smile4ever** [comment]
Allow WebExtensions to read preference browser.tabs.warnOnCloseOtherTabs
https://bugzilla.mozilla.org/show_bug.cgi?id=1376394

**Comment by Smile4ever** [comment]
The bug is about this dialog not showing when using close tabs underneath from within Tab Center Redux. @eoger says in order to implement this correctly, we need to be able to read "warnOnCloseOtherTabs" to display a warning / don't display a warning, depending on the user preferences.

![dialog](https://user-images.githubusercontent.com/544411/29078502-e1dd95cc-7c5a-11e7-9440-3d6800411468.png)

This has been added to the weekly WebExtensions triage meeting of August 8, at 17:30 UTC.

Info: https://wiki.mozilla.org/Add-ons/Contribute/Triage
Join: https://v.mozilla.com/flex.html?roomdirect.html&key=63EeximucvH3QIFBKbpuBCVBAQU
Agenda: https://docs.google.com/document/d/1I-i1FQ38nwFHNl4hnzTctdsYHXOjJpeAgm1Bm3VoUUA/edit#

@eoger Would you be able to join us?

**Comment by Smile4ever** [comment]
I was at the triage meeting. The second approach was approved. Hopefully the prompt option will get implemented. For details, see https://bugzilla.mozilla.org/show_bug.cgi?id=1388462

**Comment by Inari-Whitebear** [comment]
Is this going anywhere? It's hilariously annoying when I close some 900 tabs due to a miss-click on a function I never use in the first place.

As a user, I don't even really care if it reads the FireFox setting for it, just have whether it asks or not as a setting in the plugin until FireFox allows it to read the normal setting?

**Comment by haarp** [comment]
As #338 seems to be a mere duplicate, I'll repeat this here. It's possible to remove such dangerous menu entries with CSS.

    /* Remove "Reload All Tabs", "Close Tabs Underneath" and "Close Other Tabs" */
    .contextmenu li:nth-child(8), .contextmenu li:nth-child(9), .contextmenu li:nth-child(10) {
        display: none;
    }

Not the same as a warning, but since I never needed these anyway, it works for me.

**Comment by ariasuni** [comment]
I didn’t realize I could hide it since there were no `id`, thank you so so much. I lost all my tabs the other day and it wasn’t enjoyable. It definitely should be in the wiki.

**Comment by Keith94** [comment]
>It definitely should be in the wiki.

[done](https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-Tweaks#hide-tab-context-menu-items-93) :)
